### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by shukon** [shukon/BDP#1]
Whether or not to use [Xamarin](https://visualstudio.microsoft.com/xamarin) for development...

**Comment by SariusRu** [comment]
Halihallo,
So ich bin jetzt endöich mal Student mit zu viel Zeit, dewegen würde ich mal anfangen zumindest die Grundarchitektur der App zu entwerfen. Da ich über die Uni Visual Studio Enterprise habe, ist zurzeit auch Xamarin enthalten, und da Xamarin inzwischen fest in VS Studio integriert ist, und ich immer noch keine Preise finden konnte, denke ich das es tatsächlich kostenlos ist, von daher würde ich das einfach mal benutzen...

**Comment by shukon** [comment]
Hi - also ich hab mich grade mal erkundigt und glaube Xamarin läuft nicht unter Linux, d.h. dann wäre ich raus.
Ich fänds auch sinnvoll für sowas wie den BDP eher OpenSource-Projekte zu nutzen, damit auch Leute mitentwickeln können, die vielleicht kein VS Studio kriegen. Aber wie gesagt, wenn man's auch so runterladen kann, ist das ja egal.
Auf der anderen Seite, wenn du das alleine machen möchtest, ist das natürlich auch ok.
Ich kenn mich nicht so gut aus mit Alternativen... hab aber auch eh erst ab März Zeit. Also, wenn du das Projekt alleine machen magst, starte gern mit Xamarin. Sonst steig ich ab März ein.

**Comment by SariusRu** [comment]
Ich habe bisher auch noch keine Ahnung von App-Entwicklung, deswegen meinte ich ja ich probiere es einfach mal. Theoretisch müsste Xamarin zumindest zum Coden in allen VS-Versionen dabeisein, und zum veröffentlichen kann man ja dann meine Version nehmen.
Ich würde mal Anfangen die Grundarchitektur zu Planen, ob man das jetzt als Xamarin-App programmiert, oder als Webpage und dann einfach eine App mit dem nativen Browser zu veröffentlichen, der dann diese Webpage anzeigt kann man ja immer noch entscheiden.
Hat jemand von euch einen guten Draht zum Büro und möchte mal rausfinden was die den von der App erwarten? Ansonsten würde ich Kochbuch, Spielesammlung und durchsuchbaren Freizeitenleitfaden einplanen…

Von: Joshua <notifications@github.com>
Gesendet: Montag, 28. Januar 2019 11:13
An: shukon/BDP <BDP@noreply.github.com>
Cc: SariusRu <samuel.rundel@live.de>; Comment <comment@noreply.github.com>
Betreff: Re: [shukon/BDP] Xamarin (#1)


Hi - also ich hab mich grade mal erkundigt und glaube Xamarin läuft nicht unter Linux, d.h. dann wäre ich raus.
Ich fänds auch sinnvoll für sowas wie den BDP eher OpenSource-Projekte zu nutzen, damit auch Leute mitentwickeln können, die vielleicht kein VS Studio kriegen. Aber wie gesagt, wenn man's auch so runterladen kann, ist das ja egal.
Auf der anderen Seite, wenn du das alleine machen möchtest, ist das natürlich auch ok.
Ich kenn mich nicht so gut aus mit Alternativen... hab aber auch eh erst ab März Zeit. Also, wenn du das Projekt alleine machen magst, starte gern mit Xamarin. Sonst steig ich ab März ein.

**Comment by shukon** [comment]
Das Büro erwartet erstmal noch nichts (also ich habs kurz im eVo angesprochen, aber es liegt ganz bei uns, was wir implementieren wollen). Kochbuch, Spielesammlung und durchsuchbarer Freizeitenleitfaden klingen super. Ich hab noch von David den Hinweis bekommen, dass die BDP-Website über typo3/php läuft und wir auch einfach mit responsive scripts arbeiten können (hast du ja auch schon angsprochen). Bei Fragen dazu können wir David fragen.
