### ISSUE TITLE
Single Sign On (SSO)

### ISSUE THREAD

**Issue by shukon** [shukon/BDP#13]
Um das einfache Einloggen zu ermöglichen, hier mal ein paar Links zu möglichen Lösungen für die einzelnen Komponenten:

Dokuwiki (scheinbar native): https://www.dokuwiki.org/auth:ad und https://www.dokuwiki.org/auth
Nextcloud: https://apps.nextcloud.com/apps/user_saml
Mattermost: https://docs.mattermost.com/deployment/sso-saml.html
~~Kufer: noch unbekannt~~ CiviCRM

Allgemein lesenswert dazu sind wahrscheinlich auch Artikel über https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language im Allgemeinen...

**Comment by triayak** [comment]
Hab mal bisschen recherchiert was es dazu an open source projekten gibt. Hab mich jetzt bisschen auf Keycloak eingeschossen und würd das mal in den Raum werfen:

[https://www.keycloak.org/](https://www.keycloak.org/) 
[Vergleich verschiedener SSO Lösungen](https://openappstack.net/2019/01/31/comparison-of-free-and-open-source-single-sign-on-solutions.html) 
[Recht neuer Blog Post zu Keycloak](https://blog.timo-reymann.de/keycloak-authentication-server-fuer-alle-faelle/)

**Comment by shukon** [comment]
[Keycloak und Nextcloud](https://stackoverflow.com/questions/48400812/sso-with-saml-keycloak-and-nextcloud)
[Set Up Keycloak Simulation](https://www.katacoda.com/keycloak/courses/keycloak/configure-keycloak)

**Comment by shukon** [comment]
Ok, Update: KeyCloak ist übertrieben nice. Läuft jetzt smooth mit ner NextCloud zusammen. Serveradresse steht im Wiki (weil das ein privater Server ist, der vllt nicht unbedingt öffentlich bekannt sein muss). Der nächste Schritt ist, KeyCloak auf https zu porten (und dann auch nextcloud und dokuwiki), dann könnten wir in die eVo-Betatestphase übergehen. Freu mich total auf den Hackathon.

**Comment by shukon** [comment]
Keycloak ist aufgesetzt und läuft. Ich schließe das erstmal, alle Infos dazu stehen im Wiki.
