### ISSUE TITLE
Automatisches Einpflegen der User-Daten

### ISSUE THREAD

**Issue by shukon** [shukon/BDP#21]
Wir werden vom Büro im Endeffekt .csv-Dateien (oder Ähnliches) bekommen, mit User-Daten und Freizeiten.
Unterschiedliche Level der Automatisierung:

  - User automatisch in den Keycloak einfügen (mit "roles", also der Gruppe)
  - User im RocketChat automatisch WebDAV zur Nextcloud hinzufügen?
  - Für die Freizeiten automatisch:
    - Nextcloud-Ordner erstellen (einen für Planung, zwei für Fotos(?))
    - Freizeit / Seminar in eigenen Nextcloud-Kalender eintragen (low prio)
    - Rocket.Chat Kanal erstellen
  - Termine von wo-auch-immer-sie-jetzt-sind (vermutlich diverse Excel-Tabellen) in den BDP-Veranstaltungskalender in der Nextcloud einfügen

Die Skripte dafür bitte wenn sie unsensibel (nutzermetadatenmäßig) sind hier im Repo pushen, sonst in den Admin-Ordner in der Nextcloud (unter Skripte oder so).

**Comment by wurstbrotfan** [comment]
[das hier](https://www.smashingmagazine.com/2018/01/understanding-using-rest-api/) kann man lesen um APIs zu verstehen

**Comment by wurstbrotfan** [comment]
Ging recht schnell zu verstehen :)
Es gibt eine ausführliche API Dokumentation von RocketChat [hier](https://rocket.chat/docs/developer-guides/rest-api/channels/create/). Um sich zu authentifizieren kann man [so](https://rocket.chat/docs/developer-guides/rest-api/personal-access-tokens/) Access Tokens erstellen. Mit meinen persönlichen Tokens sah das dann so aus,und es hat funktioniert:

curl -H "X-Auth-Token: JtY(... redacted ...)xyz" 
-H "X-User-Id: JE (... redacted ...) 8m" 
-H "Content-type: application/json" 
http://217.160.13.225:3000/api/v1/channels.create 
-d '{ "name": "apichannelname" }'
