### ISSUE TITLE
Wiki offline nutzen?

### ISSUE THREAD

**Issue by mr-ml** [shukon/BDP#6]
- [ ] Backup-Routine schreiben
 - [ ] Offline-Access? Referenzen suchen!

**Comment by mr-ml** [comment]
- [ ] Wiki Baum

**Comment by mr-ml** [comment]
- [ ] Schlagwörter für Suchfunktion

**Comment by wurstbrotfan** [comment]
es gibt ein plugin, zuletzt geändert 2009. bisher nicht ausgecheckt. vllt läufts ja (bin skeptisch)
https://www.dokuwiki.org/plugin:offline

**Comment by wurstbrotfan** [comment]
es gibt eine [dokuwiki_on_a_stick version](https://www.dokuwiki.org/install:dokuwiki_on_a_stick). benötigt allerdings scheinbar Microsoft Visual Studios libraries und läuft daher evtl nur auf windows pcs, also v.a. nicht auf smartphones, wo offline nutzung wohl am dringendsten wäre...

**Comment by wurstbrotfan** [comment]
aktuell kann man ja im wiki relativ easy pdfs runterladen, also wenn man vorher weiß was man offline braucht kann man sich das von dort aufs handy/laptop runterladen.
für ein echtes offline-erlebnis auf dem handy braucht's halt eine app die mehr kann als webviews anzeigen...

**Comment by markusu49** [comment]
Was genau soll die Offline-Version denn können?

- ausgewählte Inhalte anzeigen ohne große Such- und Navigationsmöglichkeiten (z.B. als PDF)
- lesender Zugriff mit Suchfunktionen (z.B. als App)
- Bearbeitungsfunktionen?

Grundsätzlich sollte es kein Problem sein, dokuwiki auf welchem System auch immer zu installieren. Das ist ja nur ein bisschen PHP-Code. Vielleicht sogar auf Android:

https://play.google.com/store/apps/details?id=ru.kslabs.ksweb

Zwei Plugins, die interessant sein könnten:

https://www.dokuwiki.org/plugin:bookcreator
https://www.dokuwiki.org/plugin:epub
