### ISSUE TITLE
Webview integrieren

### ISSUE THREAD

**Issue by shukon** [shukon/BDP#7]
Webview für Mattermost / Dokuwiki / Nextcloud in das App-Framework integrieren

**Comment by sunyes2** [comment]
wiki, cloud and calendar link added

**Comment by shukon** [comment]
Aktuell ist das Umschalten zwischen den Webviews nicht möglich. Warum nicht und wie können wir das ändern?

Außerdem: können wir die Webviews auf ihre Domains beschränken, s.d. z.B. externe Links immer im echten Browser geöffnet werden und nicht in der App? Allerdings bei Klick auf Nextcloud einfach in den Nextcloud-Tab gewechselt wird?
