### ISSUE TITLE
Flutter Webapp

### ISSUE THREAD

**Issue by shukon** [shukon/BDP#8]
Die Flutter Webvariante (neben Android und iOS) ...
- [ ] testen
- [ ] in die Website integrieren

Note: Aktuell ist die Webapp von flutter noch in der Experimentierphase, mehr Infos [hier](https://flutter.dev/web).

**Comment by wurstbrotfan** [comment]
geschlossen, weil wir (stand jetzt) die drei dienste (chat, cloud, wiki) einfach im browser nutzen werden und daher keine web-version der app brauchen
